
export const ProjectList = [
    {
      name: "Bateaux Massage",
      image: "https://firebasestorage.googleapis.com/v0/b/chat1-b013f.appspot.com/o/Project1.png?alt=media&token=984ee6ce-5b93-492c-b5b4-d5ee3d011e6a",
      skills: "HTML, CSS, JavaScript, Bootstrap",
      sourceCode: "https://github.com/varuscritical900/varuscritical900.github.io",
      liveLink: "https://varuscritical900.github.io/",
      description: "Bateaux Massage - is a mini project that I developed during my time at KodeGo, a bootcamp company. The project uses a combination of HTML5, CSS, and a little bit of JavaScript, with 40% Bootstrap used to assist in the design. However, most of the design was done with personalized CSS, which means that I put in a lot of effort to create a unique and visually appealing design. From the project name, it appears that Bateaux Massage is related to massage services that might be provided on a boat, or at home, hotel or in spa. My website include information about different types of massages, hair styles, and other services available, it also include pricing, contact information, and possibly even an appointment booking system. This is a Front-End Design only and recevied The KodeGo Five Star Web Application Award is a recognition of the high quality of your work. It indicates that your project was not only visually appealing but also functional, user-friendly, and met the requirements of the project brief. Overall, this is a great achievement and a testament to your hard work and skill in web development."
    },
    {
      name: "TravelKode",
      image: "https://firebasestorage.googleapis.com/v0/b/chat1-b013f.appspot.com/o/Project2.png?alt=media&token=1f242d89-30c8-4c66-b297-3d72dab9255d",
      skills: "React, Node.js, Json Server",
      sourceCode: "https://github.com/varuscritical900/travelkode-mini-project-2",
      liveLink: "https://travelkode-mini-project-2-jwlvaov90-varuscritical900.vercel.app/",
      description:"TravelKode - is a mini project developed using React and SASS, as part of the KodeGo bootcamp. The website has been designed to provide an easy-to-use platform for both travelers and tour operators. The website offers a comprehensive CRUD functionality, allowing users to create, edit, view, or delete tours. This feature enables tour operators to manage their tour services efficiently while providing travelers with a seamless booking experience. With TravelKode, travelers can browse and book tours based on their preferences and budget. The website displays a list of available tours, along with the tour details, such as price, duration, and itinerary. Travelers can view the tours' details and book their preferred tour by selecting the appropriate tour and providing their details. Tour operators can offer their tour services by adding their tours to the platform. They can create and manage their tours by adding relevant information, such as tour name, description, itinerary, and price. The platform also allows tour operators to edit or delete their tours as needed. The website's design is sleek and modern, with a focus on user experience. The use of SASS for design enhances the website's aesthetics, making it visually appealing and easy to navigate. Overall, TravelKode is a functional and user-friendly platform that allows travelers to explore and book tours while providing tour operators with an efficient way to offer their tour services."
    },
    {
      name: "Kodegram",
      image: "https://firebasestorage.googleapis.com/v0/b/chat1-b013f.appspot.com/o/Capstone%20Project.png?alt=media&token=e4d74a82-b25a-4500-a99a-1a790b1a13df",
      skills: "React, MonggoDB, Express, Node.js, Firebase",
      sourceCode: "https://github.com/kt1422/kodegram",
      liveLink: "https://kodegram.devph.space/",
      description:"This is our final Capstone Project for our Codecamp in KodeGo and we named the project Kodegram Kodegram - is a fullstack web application developed by a team of four using the MERN stack, Firebase, and Sass for customized CSS. The purpose of Kodegram is to provide a social media platform that is similar to Instagram in terms of its features and functionalities. The name Kodegram is derived from the name of the code camp attended by the development team, KodeGo, and the popular social media platform Instagram. This name reflects the inspiration behind the project and the team's goal to create a unique and innovative social media platform. Using the MERN stack, Kodegram leverages the power of MongoDB, Express, React, and Node.js to provide a seamless user experience. Firebase is used for authentication, database management, while SASS is used to create personalized CSS styles that are unique to Kodegram. The development team has worked tirelessly to create a user-friendly interface that includes a range of features such as photo sharing, user profiles, a news feed, likes, comments, and direct messaging. The team has also implemented advanced search functionality to help users discover new content and connect with other users. Overall, Kodegram is an exciting project that showcases the power of modern web development tools and technologies. The development team has put in a tremendous amount of effort to create a platform that is both user-friendly and innovative, and they are excited to share their creation with the world. This project was awarded as Best Capstone project on our batch(WD37)"
    },
    {
      name: "Give Aid",
      image: "https://firebasestorage.googleapis.com/v0/b/chat1-b013f.appspot.com/o/e-project-qatar.jpg?alt=media&token=0dda8d4d-b674-4ee7-8f5d-3e3b6512aefd",
      skills: "C#, .NET, .ASP MVC, jquery",
      liveLink: "#",
      description:"Give Aid - was my final project for Aptech Qatar wayback 2018, created using C# ASP.NET MVC, MS SQL, and jQuery. The project was designed to support a non-governmental organization (NGO) that allowed people to donate to the poor. The system allowed users to make donations and monitor their donations over time. The system also allowed the NGO to keep track of donations and manage their finances more effectively. The system was built with a responsive design, making it accessible on both desktop and mobile devices. To create this project, I used my skills in C# ASP.NET MVC and jQuery to build a robust and user-friendly system. I utilized MS SQL to manage the backend database and ensure that the system could store and retrieve data quickly and accurately. Although this project was created in 2018, I am currently working on finding the original files so that I can deploy the project to Github and make it available for others to review. I believe that this project represents my skills as a developer and my ability to create systems that can make a difference in the world."
    },
    {
      name: "This Portfolio",
      image: "https://firebasestorage.googleapis.com/v0/b/chat1-b013f.appspot.com/o/portolio.png?alt=media&token=b3e8262a-22f7-4b4d-9746-5374d8a82ff2",
      skills: "React, Vite",
      sourceCode: "https://github.com/varuscritical900/marc2",
      liveLink: "https://www.marc2.vercel.app/",
      description:"Welcome to my portfolio! As a Full-Stack developer, I wanted to create a website that showcases my skills and capabilities. That's why I decided to develop this website using React Vite, React Router DOM, React Icons, Motion Framer, Bootstrap, and CRUD functionality. I have implemented CRUD functionality, However for this portfolio I only Impelemented only the Read to view a certain project and to know more about my previous projects as read functionality is only necessary for this project. CRUD is allowing users to Create, Read, Update, and Delete data from the website. This functionality is particularly useful for a wide range of applications, and I am excited to showcase my skills in this area. Bootstrap has allowed me to add an additional touch to the website, making it more responsive and visually appealing. With Bootstrap's extensive set of pre-built components, I was able to create a consistent and polished design that works well on all devices. I wanted the website to be visually engaging and easy to navigate. With React Router DOM, users can move between pages seamlessly, while the Motion Framer component adds smooth transitions and animations to create an immersive experience. The use of React Icons has also allowed me to add a touch of personality to the website, while still keeping it functional. But it's not just about the design. I've also used React to create functional and interactive components that demonstrate my understanding of React's core concepts. By utilizing React Hooks, I've managed state effectively, allowing users to interact with the website seamlessly. Overall, my portfolio is a testament to my skills as a React developer. I hope you enjoy exploring the website and getting a sense of what I can offer as a developer. Please feel free to contact me with any questions or feedback you may have, you can contact me at varuscritical900@gmail.com or directly call me at 09466610015(Philippines)."
    },
  ];